# Generated by Django 3.1.3 on 2021-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('analytic_points', models.IntegerField()),
                ('develop_points', models.IntegerField()),
                ('test_points', models.IntegerField()),
                ('business_value', models.IntegerField()),
            ],
        ),
    ]
