# Generated by Django 3.0.7 on 2021-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name_plural': 'User Stories'},
        ),
        migrations.AlterField(
            model_name='card',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='row_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='dayNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wip_limit1',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='wip_limit2',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='wip_limit3',
            field=models.IntegerField(default=4),
        ),
    ]
