# Generated by Django 3.0.7 on 2021-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_room_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='business_value_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='business_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='dayNum',
            field=models.IntegerField(default=1),
        ),
    ]
