# Generated by Django 3.1.3 on 2021-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_card_business_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='spectator',
            field=models.BooleanField(default=False),
        ),
    ]
