# Generated by Django 3.1.3 on 2021-06-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210626_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ready_day',
            field=models.IntegerField(default=-1),
        ),
    ]
